name: "default"
env:
 CI: 1
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        name: csound-wasm
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Install apt-get dependencies
      run: sudo apt-get install zip
    - name: Install npm dependencies via yarn
      run: yarn
    - name: Test
      run: yarn lint
    - name: Compile csound natively to wasm
      run: nix-build -E '(with import <nixpkgs> {}; import ./nix/native/compile.nix)' -o result_compile
    - name: Build javascript bundles
      run: |
          yarn release
          rm dist/__*
          zip -r dist.zip dist
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist.zip
